export type CanonBook = {
  id: string;
  chapters: number;
  nameEs: string;
  nameEn: string;
  abbreviationEs: string;
  abbreviationEn: string;
  testament: 'old' | 'new';
  aliases: string[];
};

export const PROTESTANT_66: readonly CanonBook[] = [
  ['GEN', 50, 'Génesis', 'Genesis', 'Gn', 'Gen', ['genesis', 'gen']],
  ['EXO', 40, 'Éxodo', 'Exodus', 'Ex', 'Exod', ['exodo', 'exodus', 'exo']],
  ['LEV', 27, 'Levítico', 'Leviticus', 'Lv', 'Lev', ['levitico', 'leviticus', 'lev']],
  ['NUM', 36, 'Números', 'Numbers', 'Nm', 'Num', ['numeros', 'numbers', 'num']],
  ['DEU', 34, 'Deuteronomio', 'Deuteronomy', 'Dt', 'Deut', ['deuteronomio', 'deuteronomy', 'deu']],
  ['JOS', 24, 'Josué', 'Joshua', 'Jos', 'Josh', ['josue', 'joshua', 'jos']],
  ['JDG', 21, 'Jueces', 'Judges', 'Jue', 'Judg', ['jueces', 'judges', 'jdg']],
  ['RUT', 4, 'Rut', 'Ruth', 'Rt', 'Ruth', ['rut', 'ruth']],
  ['1SA', 31, '1 Samuel', '1 Samuel', '1 S', '1 Sam', ['1 samuel', '1sa', 'primera de samuel']],
  ['2SA', 24, '2 Samuel', '2 Samuel', '2 S', '2 Sam', ['2 samuel', '2sa', 'segunda de samuel']],
  ['1KI', 22, '1 Reyes', '1 Kings', '1 R', '1 Kgs', ['1 reyes', '1 kings', '1ki', 'primera de reyes']],
  ['2KI', 25, '2 Reyes', '2 Kings', '2 R', '2 Kgs', ['2 reyes', '2 kings', '2ki', 'segunda de reyes']],
  ['1CH', 29, '1 Crónicas', '1 Chronicles', '1 Cr', '1 Chr', ['1 cronicas', '1 chronicles', '1ch', 'primera de cronicas']],
  ['2CH', 36, '2 Crónicas', '2 Chronicles', '2 Cr', '2 Chr', ['2 cronicas', '2 chronicles', '2ch', 'segunda de cronicas']],
  ['EZR', 10, 'Esdras', 'Ezra', 'Esd', 'Ezra', ['esdras', 'ezra', 'ezr']],
  ['NEH', 13, 'Nehemías', 'Nehemiah', 'Neh', 'Neh', ['nehemias', 'nehemiah', 'neh']],
  ['EST', 10, 'Ester', 'Esther', 'Est', 'Esth', ['ester', 'esther', 'est']],
  ['JOB', 42, 'Job', 'Job', 'Job', 'Job', ['job']],
  ['PSA', 150, 'Salmos', 'Psalms', 'Sal', 'Ps', ['salmo', 'salmos', 'psalm', 'psalms', 'psa']],
  ['PRO', 31, 'Proverbios', 'Proverbs', 'Pr', 'Prov', ['proverbios', 'proverbs', 'pro']],
  ['ECC', 12, 'Eclesiastés', 'Ecclesiastes', 'Ec', 'Eccl', ['eclesiastes', 'ecclesiastes', 'ecc']],
  ['SNG', 8, 'Cantares', 'Song of Solomon', 'Cnt', 'Song', ['cantares', 'cantar de los cantares', 'song of solomon', 'song', 'sng']],
  ['ISA', 66, 'Isaías', 'Isaiah', 'Is', 'Isa', ['isaias', 'isaiah', 'isa']],
  ['JER', 52, 'Jeremías', 'Jeremiah', 'Jer', 'Jer', ['jeremias', 'jeremiah', 'jer']],
  ['LAM', 5, 'Lamentaciones', 'Lamentations', 'Lm', 'Lam', ['lamentaciones', 'lamentations', 'lam']],
  ['EZK', 48, 'Ezequiel', 'Ezekiel', 'Ez', 'Ezek', ['ezequiel', 'ezekiel', 'ezk']],
  ['DAN', 12, 'Daniel', 'Daniel', 'Dn', 'Dan', ['daniel', 'dan']],
  ['HOS', 14, 'Oseas', 'Hosea', 'Os', 'Hos', ['oseas', 'hosea', 'hos']],
  ['JOL', 3, 'Joel', 'Joel', 'Jl', 'Joel', ['joel', 'jol']],
  ['AMO', 9, 'Amós', 'Amos', 'Am', 'Amos', ['amos', 'amo']],
  ['OBA', 1, 'Abdías', 'Obadiah', 'Abd', 'Obad', ['abdias', 'obadiah', 'oba']],
  ['JON', 4, 'Jonás', 'Jonah', 'Jon', 'Jonah', ['jonas', 'jonah', 'jon']],
  ['MIC', 7, 'Miqueas', 'Micah', 'Mi', 'Mic', ['miqueas', 'micah', 'mic']],
  ['NAM', 3, 'Nahúm', 'Nahum', 'Nah', 'Nah', ['nahum', 'nam']],
  ['HAB', 3, 'Habacuc', 'Habakkuk', 'Hab', 'Hab', ['habacuc', 'habakkuk', 'hab']],
  ['ZEP', 3, 'Sofonías', 'Zephaniah', 'Sof', 'Zeph', ['sofonias', 'zephaniah', 'zep']],
  ['HAG', 2, 'Hageo', 'Haggai', 'Hag', 'Hag', ['hageo', 'haggai', 'hag']],
  ['ZEC', 14, 'Zacarías', 'Zechariah', 'Zac', 'Zech', ['zacarias', 'zechariah', 'zec']],
  ['MAL', 4, 'Malaquías', 'Malachi', 'Mal', 'Mal', ['malaquias', 'malachi', 'mal']],
  ['MAT', 28, 'Mateo', 'Matthew', 'Mt', 'Matt', ['mateo', 'matthew', 'mat']],
  ['MRK', 16, 'Marcos', 'Mark', 'Mr', 'Mark', ['marcos', 'mark', 'mrk']],
  ['LUK', 24, 'Lucas', 'Luke', 'Lc', 'Luke', ['lucas', 'luke', 'luk']],
  ['JHN', 21, 'Juan', 'John', 'Jn', 'John', ['juan', 'john', 'jhn']],
  ['ACT', 28, 'Hechos', 'Acts', 'Hch', 'Acts', ['hechos', 'acts', 'act']],
  ['ROM', 16, 'Romanos', 'Romans', 'Ro', 'Rom', ['romanos', 'romans', 'rom']],
  ['1CO', 16, '1 Corintios', '1 Corinthians', '1 Co', '1 Cor', ['1 corintios', '1 corinthians', '1co', 'primera de corintios']],
  ['2CO', 13, '2 Corintios', '2 Corinthians', '2 Co', '2 Cor', ['2 corintios', '2 corinthians', '2co', 'segunda de corintios']],
  ['GAL', 6, 'Gálatas', 'Galatians', 'Gá', 'Gal', ['galatas', 'galatians', 'gal']],
  ['EPH', 6, 'Efesios', 'Ephesians', 'Ef', 'Eph', ['efesios', 'ephesians', 'eph']],
  ['PHP', 4, 'Filipenses', 'Philippians', 'Fil', 'Phil', ['filipenses', 'philippians', 'php']],
  ['COL', 4, 'Colosenses', 'Colossians', 'Col', 'Col', ['colosenses', 'colossians', 'col']],
  ['1TH', 5, '1 Tesalonicenses', '1 Thessalonians', '1 Ts', '1 Thess', ['1 tesalonicenses', '1 thessalonians', '1th', 'primera de tesalonicenses']],
  ['2TH', 3, '2 Tesalonicenses', '2 Thessalonians', '2 Ts', '2 Thess', ['2 tesalonicenses', '2 thessalonians', '2th', 'segunda de tesalonicenses']],
  ['1TI', 6, '1 Timoteo', '1 Timothy', '1 Ti', '1 Tim', ['1 timoteo', '1 timothy', '1ti', 'primera de timoteo']],
  ['2TI', 4, '2 Timoteo', '2 Timothy', '2 Ti', '2 Tim', ['2 timoteo', '2 timothy', '2ti', 'segunda de timoteo']],
  ['TIT', 3, 'Tito', 'Titus', 'Tit', 'Titus', ['tito', 'titus', 'tit']],
  ['PHM', 1, 'Filemón', 'Philemon', 'Flm', 'Phlm', ['filemon', 'philemon', 'phm']],
  ['HEB', 13, 'Hebreos', 'Hebrews', 'Heb', 'Heb', ['hebreos', 'hebrews', 'heb']],
  ['JAS', 5, 'Santiago', 'James', 'Stg', 'Jas', ['santiago', 'james', 'jas']],
  ['1PE', 5, '1 Pedro', '1 Peter', '1 P', '1 Pet', ['1 pedro', '1 peter', '1pe', 'primera de pedro']],
  ['2PE', 3, '2 Pedro', '2 Peter', '2 P', '2 Pet', ['2 pedro', '2 peter', '2pe', 'segunda de pedro']],
  ['1JN', 5, '1 Juan', '1 John', '1 Jn', '1 John', ['1 juan', '1 john', '1jn', 'primera de juan']],
  ['2JN', 1, '2 Juan', '2 John', '2 Jn', '2 John', ['2 juan', '2 john', '2jn', 'segunda de juan']],
  ['3JN', 1, '3 Juan', '3 John', '3 Jn', '3 John', ['3 juan', '3 john', '3jn', 'tercera de juan']],
  ['JUD', 1, 'Judas', 'Jude', 'Jud', 'Jude', ['judas', 'jude', 'jud']],
  ['REV', 22, 'Apocalipsis', 'Revelation', 'Ap', 'Rev', ['apocalipsis', 'revelation', 'rev']],
].map(
  ([id, chapters, nameEs, nameEn, abbreviationEs, abbreviationEn, aliases], index) => ({
    id: id as string,
    chapters: chapters as number,
    nameEs: nameEs as string,
    nameEn: nameEn as string,
    abbreviationEs: abbreviationEs as string,
    abbreviationEn: abbreviationEn as string,
    aliases: aliases as string[],
    testament: index < 39 ? 'old' : 'new',
  }),
);
